create database mmstechnologybank;
use mmstechnologybank;
CREATE TABLE USERS (
    USERNAME VARCHAR(128) PRIMARY KEY,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
);


CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(128) NOT NULL,
    AUTHORITY VARCHAR(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHusersORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

INSERT INTO users (USERNAME, PASSWORD, ENABLED)
VALUES ('happy', '12345', 'Y');

INSERT INTO authorities (USERNAME, AUTHORITY) values ('happy', 'write');


CREATE TABLE CUSTOMER (
	`id` INT NOT NULL auto_increment,
    `email` VARCHAR(45) NOT NULL,
    `pwd` VARCHAR(200) NOT NULL,
    `role` VARCHAR(45) NOT NULL,
    primary key(`id`)
);

INSERT INTO Customer (`email`, `pwd`, `role`)
	VALUES('a@a.com','123','admin');

SELECT * FROM mmstechnologybank.customer;